# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ml_service_pb2 as ml__service__pb2


class MLServiceStub(object):
    """Сервис для работы с ML моделями"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
            "/mlservice.MLService/HealthCheck",
            request_serializer=ml__service__pb2.HealthRequest.SerializeToString,
            response_deserializer=ml__service__pb2.HealthResponse.FromString,
        )
        self.GetModelTypes = channel.unary_unary(
            "/mlservice.MLService/GetModelTypes",
            request_serializer=ml__service__pb2.ModelTypesRequest.SerializeToString,
            response_deserializer=ml__service__pb2.ModelTypesResponse.FromString,
        )
        self.TrainModel = channel.unary_unary(
            "/mlservice.MLService/TrainModel",
            request_serializer=ml__service__pb2.TrainModelRequest.SerializeToString,
            response_deserializer=ml__service__pb2.TrainModelResponse.FromString,
        )
        self.RetrainModel = channel.unary_unary(
            "/mlservice.MLService/RetrainModel",
            request_serializer=ml__service__pb2.RetrainModelRequest.SerializeToString,
            response_deserializer=ml__service__pb2.TrainModelResponse.FromString,
        )
        self.Predict = channel.unary_unary(
            "/mlservice.MLService/Predict",
            request_serializer=ml__service__pb2.PredictRequest.SerializeToString,
            response_deserializer=ml__service__pb2.PredictResponse.FromString,
        )
        self.ListModels = channel.unary_unary(
            "/mlservice.MLService/ListModels",
            request_serializer=ml__service__pb2.ListModelsRequest.SerializeToString,
            response_deserializer=ml__service__pb2.ListModelsResponse.FromString,
        )
        self.DeleteModel = channel.unary_unary(
            "/mlservice.MLService/DeleteModel",
            request_serializer=ml__service__pb2.DeleteModelRequest.SerializeToString,
            response_deserializer=ml__service__pb2.DeleteModelResponse.FromString,
        )
        self.ListDatasets = channel.unary_unary(
            "/mlservice.MLService/ListDatasets",
            request_serializer=ml__service__pb2.ListDatasetsRequest.SerializeToString,
            response_deserializer=ml__service__pb2.ListDatasetsResponse.FromString,
        )


class MLServiceServicer(object):
    """Сервис для работы с ML моделями"""

    def HealthCheck(self, request, context):
        """Проверка здоровья сервиса"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetModelTypes(self, request, context):
        """Получение списка доступных типов моделей"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TrainModel(self, request, context):
        """Обучение модели"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RetrainModel(self, request, context):
        """Переобучение существующей модели"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Predict(self, request, context):
        """Предсказание"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListModels(self, request, context):
        """Список моделей"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteModel(self, request, context):
        """Удаление модели"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListDatasets(self, request, context):
        """Список датасетов"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=ml__service__pb2.HealthRequest.FromString,
            response_serializer=ml__service__pb2.HealthResponse.SerializeToString,
        ),
        "GetModelTypes": grpc.unary_unary_rpc_method_handler(
            servicer.GetModelTypes,
            request_deserializer=ml__service__pb2.ModelTypesRequest.FromString,
            response_serializer=ml__service__pb2.ModelTypesResponse.SerializeToString,
        ),
        "TrainModel": grpc.unary_unary_rpc_method_handler(
            servicer.TrainModel,
            request_deserializer=ml__service__pb2.TrainModelRequest.FromString,
            response_serializer=ml__service__pb2.TrainModelResponse.SerializeToString,
        ),
        "RetrainModel": grpc.unary_unary_rpc_method_handler(
            servicer.RetrainModel,
            request_deserializer=ml__service__pb2.RetrainModelRequest.FromString,
            response_serializer=ml__service__pb2.TrainModelResponse.SerializeToString,
        ),
        "Predict": grpc.unary_unary_rpc_method_handler(
            servicer.Predict,
            request_deserializer=ml__service__pb2.PredictRequest.FromString,
            response_serializer=ml__service__pb2.PredictResponse.SerializeToString,
        ),
        "ListModels": grpc.unary_unary_rpc_method_handler(
            servicer.ListModels,
            request_deserializer=ml__service__pb2.ListModelsRequest.FromString,
            response_serializer=ml__service__pb2.ListModelsResponse.SerializeToString,
        ),
        "DeleteModel": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteModel,
            request_deserializer=ml__service__pb2.DeleteModelRequest.FromString,
            response_serializer=ml__service__pb2.DeleteModelResponse.SerializeToString,
        ),
        "ListDatasets": grpc.unary_unary_rpc_method_handler(
            servicer.ListDatasets,
            request_deserializer=ml__service__pb2.ListDatasetsRequest.FromString,
            response_serializer=ml__service__pb2.ListDatasetsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "mlservice.MLService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class MLService(object):
    """Сервис для работы с ML моделями"""

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.MLService/HealthCheck",
            ml__service__pb2.HealthRequest.SerializeToString,
            ml__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetModelTypes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.MLService/GetModelTypes",
            ml__service__pb2.ModelTypesRequest.SerializeToString,
            ml__service__pb2.ModelTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def TrainModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.MLService/TrainModel",
            ml__service__pb2.TrainModelRequest.SerializeToString,
            ml__service__pb2.TrainModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RetrainModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.MLService/RetrainModel",
            ml__service__pb2.RetrainModelRequest.SerializeToString,
            ml__service__pb2.TrainModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Predict(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.MLService/Predict",
            ml__service__pb2.PredictRequest.SerializeToString,
            ml__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListModels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.MLService/ListModels",
            ml__service__pb2.ListModelsRequest.SerializeToString,
            ml__service__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeleteModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.MLService/DeleteModel",
            ml__service__pb2.DeleteModelRequest.SerializeToString,
            ml__service__pb2.DeleteModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListDatasets(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mlservice.MLService/ListDatasets",
            ml__service__pb2.ListDatasetsRequest.SerializeToString,
            ml__service__pb2.ListDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
